// Individual Stats Action Types
export const GET_PLAYER_SEASONS = 'GET_PLAYER_SEASONS';
export const LOADING_STATS = 'LOADING_STATS';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_PERSPECTIVE = 'SET_PERSPECTIVE';
export const SET_SEASON = 'SET_SEASON';
export const REFRESH_PLAYER_SEASONS = 'REFRESH_PLAYER_SEASONS';
export const SET_ERROR = 'SET_ERROR';

// Together Stats Action Types
export const SET_SQUAD_MEMBERS = 'SET_SQUAD_MEMBERS';
export const SET_SQUAD_MEMBERS_FETCHED = 'SET_SQUAD_MEMBERS_FETCHED';
export const SET_SQUAD_MEMBERS_COLORS = 'SET_SQUAD_MEMBERS_COLORS';
export const SET_SQUAD_GAME_MODE = 'SET_SQUAD_GAME_MODE';
export const SET_SQUAD_PERSPECTIVE = 'SET_SQUAD_PERSPECTIVE';
export const SELECT_PLAYER = 'SET_PLAYER';
export const GET_SQUAD_STATS = 'GET_SQUAD_STATS';
export const LOADING_SQUAD_STATS = 'LOADING_SQUAD_STATS';
export const SET_SQUAD_ERROR = 'SET_SQUAD_ERROR';

// Auth Action Types
export const GET_AUTH_ERRORS = 'GET_AUTH_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_FACEBOOK = 'AUTHENTICATE_FACEBOOK';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const RESTORE_AUTH_STATE = 'RESTORE_AUTH_STATE';
